### PR TITLE
feature to submit jobs with tags and corresponding tests.

### PR DESCRIPTION
**Pull request by aopy**

### CODE REVIEW

**Comment by rowleya** [comment]
Is "tags" going to be a new field that occurs in all jobs?

**Comment by aopy** [comment]
Yes, this is a continuation of the work in the neuromorphic platform: https://github.com/HumanBrainProject/hbp_neuromorphic_platform/pull/12

**Comment by rowleya** [comment]
OK - missed that one.  Are these changes live on the server?

**Comment by apdavison** [comment]
@rowleya no, the changes aren't on the production server yet. They're deployed on the staging server. Will this have an impact on you?

**Comment by rowleya** [comment]
I am not sure if it will, though I suspect it might.  The job object we hold doesn't have a tag field.  I believe that the field will therefore be ignored.  The issue would then arise when sending updated jobs back to the server, which won't have the tag field in them.  I can add this as an issue for our side of the server.

**Comment by apdavison** [comment]
ok, thanks for the update. I was hoping to deploy this on the production server no later than October 3rd, to give us two weeks to iron out any problems before the HBP Summit. Is that enough time for you to update your system?

**Comment by rowleya** [comment]
Yes, this should be fine - I have added the issue so I will have a look at it shortly.

**Pull request merged**
